### ISSUE TITLE
Не загружается приложение KeyError: slash

### ISSUE THREAD

**Issue by reef425** [ikamensh/drim_gam#11]
Вывод из console
slash
Traceback (most recent call last):
  File "launch.py", line 6, in <module>
    from content.dungeons.demo_dungeon import demo_dungeon
  File "/pydolons/content/dungeons/demo_dungeon.py", line 8, in <module>
    pirate_band = [pirate.create() for i in range(3)]
  File "/pydolons/content/dungeons/demo_dungeon.py", line 8, in <listcomp>
    pirate_band = [pirate.create() for i in range(3)]
  File "/pydolons/game_objects/monsters/Monster.py", line 29, in create
    unit.masteries = Masteries.max_out(self.base_type.xp, unit.melee_mastery)
  File "/pydolons/character_creation/Masteries.py", line 70, in max_out
    _masteries.exp_spent[chosen] += exp - distributed_xp

**Comment by ikamensh** [comment]
Привет, полный ли это traceback?
я не могу понять у какого объекта небыло Key: slash

В текущей версии я не вижу этой ошибки.

**Comment by reef425** [comment]
После обновлений ошибка пропала
