### ISSUE TITLE
Проблема с импортом пакета, возможно циклический импорт

### ISSUE THREAD

**Issue by reef425** [ikamensh/drim_gam#13]
Вывод в лог

```slash
Traceback (most recent call last):
  File "launch.py", line 3, in <module>
    from character_creation.Character import Character
  File "/pydolons/character_creation/Character.py", line 3, in <module>
    from game_objects.battlefield_objects import BaseType, Unit, CharAttributes
  File "/pydolons/game_objects/battlefield_objects/__init__.py", line 4, in <module>
    from game_objects.battlefield_objects.Unit import Unit
  File "/pydolons/game_objects/battlefield_objects/Unit.py", line 4, in <module>
    from game_objects.items import Inventory, Equipment, Weapon
  File "/pydolons/game_objects/items/__init__.py", line 7, in <module>
    from game_objects.items.WearableItem import WearableItem
  File "/pydolons/game_objects/items/WearableItem.py", line 3, in <module>
    from mechanics.events import ItemDestroyedEvent
  File "/pydolons/mechanics/events/__init__.py", line 25, in <module>
    from mechanics.events.MovementEvent import MovementEvent
  File "/pydolons/mechanics/events/MovementEvent.py", line 3, in <module>
    from battlefield import Cell
  File "/pydolons/battlefield/__init__.py", line 2, in <module>
    from battlefield.Battlefield import Battlefield
  File "/pydolons/battlefield/Battlefield.py", line 4, in <module>
    import game_objects.battlefield_objects as bf_objs
AttributeError: module 'game_objects' has no attribute 'battlefield_objects'

**Comment by reef425** [comment]
Проблему устранил путем перенесения импорта пакета в метод.

Модуль battlefield/Battlefield.py
Метод 

```
def distance(self, one, another):
        import game_objects.battlefield_objects as bf_objs
        ***
        pass

**Comment by reef425** [comment]
Предположительно в одном из импортированных модулей 
`game_objects/battlefield_objects`
Существует ссылка на еще не созданный объект Battlefield.py

**Comment by ikamensh** [comment]
Известные случаи этой проблемы исправлены
